# Generated by Django 5.0.4 on 2024-05-01 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_pais_options_alter_cliente_pais_origen_id_and_more'),
        ('producto', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='cliente')),
                ('producto_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='cliente')),
            ],
        ),
    ]
