# Generated by Django 5.0.4 on 2024-05-23 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_infoproductopedido_delete_infoproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoproductopedido',
            options={'ordering': ('fecha_venta',)},
        ),
        migrations.AddField(
            model_name='infoproductopedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infoproductopedido',
            name='fecha_venta',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='infoproductopedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
