# Generated by Django 5.0.4 on 2024-05-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.productocategoria', verbose_name='Categoria de producto'),
        ),
    ]
