# Generated by Django 5.0.4 on 2024-05-23 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Fecha de actualizacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_disponible',
            field=models.FloatField(default=0),
        ),
    ]
